/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ext_testing_JniPlt */

#ifndef _Included_ext_testing_JniPlt
#define _Included_ext_testing_JniPlt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ext_testing_JniPlt
 * Method:    testfunc
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ext_testing_JniPlt_testfunc
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
